"""change column name

Revision ID: 036287db3786
Revises: 2ab31a05b1fc
Create Date: 2025-05-08 23:06:39.233999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036287db3786'
down_revision = '2ab31a05b1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_pixels', sa.Integer(), nullable=True))
        batch_op.drop_column('other_pixels')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_pixels', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_pixels')

    # ### end Alembic commands ###
